server:
  port: 2222
spring:
  application:
    name: demo-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
#  instance:
#    hostname: ribbon
     # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。
     #turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整